<<<<<<< HEAD
# Generated by Django 5.0 on 2023-12-22 02:40
=======
# Generated by Django 5.0 on 2023-12-21 17:11
>>>>>>> aee1b4fd0e0c1a1ea9ebd2872b05184f9766ff76

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)ss', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='%(app_label)s_%(class)s_set', related_query_name='%(app_label)s_%(class)ss', to='auth.permission'),
        ),
    ]
