# Generated by Django 4.2.7 on 2023-12-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
