# Generated by Django 4.2.7 on 2023-12-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_categorias_publicaciones_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='subtitulo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
