# Generated by Django 5.0 on 2023-12-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_publicaciones_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(default='default', upload_to=''),
        ),
    ]
