# Generated by Django 4.2.7 on 2023-12-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_alter_publicaciones_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(upload_to='publicaciones'),
        ),
    ]
