# Generated by Django 4.2.7 on 2023-12-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0006_merge_20231225_2050'),
        ('publicaciones', '0007_alter_publicaciones_imagen'),
    ]

    operations = [
    ]
