# Generated by Django 5.0 on 2023-12-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_merge_20231227_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='img',
        ),
    ]
